services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "82:8082"
    networks:
      - app-network
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: python3 main.py
    networks:
      - app-network
    environment:
      - LLM_API_KEY=${LLM_API_KEY}

networks:
  app-network:
    driver: bridge