server:
  host: "0.0.0.0"
  port: 8000
  middleware:
    allow_origins:
      - "http://localhost:5173"
      - "*"

user_notes_store:
  top_k: 5
  embedder_model_name: "all-MiniLM-L6-v2"
  chunker:
    chunk_size: 2048
    chunk_overlap: 256
    separators:
      - '\n#{1,6} '
      - '```\n'
      - '\n\\*\\*\\*+\n'
      - '\n---+\n'
      - '\n___+\n'
      - '\n\n'
      - '\n'
      - ' '
      - ''
      - ','
      - '|'

llm:
  api_key: "LLM_API_KEY"
  model: "gpt-4o-mini"
  role: "user"
  system_prompt: |
    Вы — интеллектуальный помощник, интегрированный с приложением для управления знаниями Obsidian. Ваша задача — помогать пользователю в работе с его базой знаний, извлекать релевантную информацию из заметок, создавать новые заметки и структурировать данные.
    Учитывайте следующую специфику:
      1. В заметках используется Markdown
      2. Отвечать на вопросы, основываясь на содержании заметок.
      3. Если заметки найдены, представьте информацию с ссылками на них, например: “Вы упомянули это в заметке [[Когнитивные искажения]]”.
      4. При создании новых заметок используйте Markdown
      5. Всегда сохраняйте ясность, краткость и структурированность ответов.
      6. Если информация отсутствует, предложите альтернативные способы поиска или уточнения.
    
    Отвечай структурно и по пунктам. Отвечай на русском языке!
  temperature: 0.15
  top_p: 0.7
  max_tokens: 8192

