name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build app
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop service
        run: docker compose -f docker-compose.yml down

      - name: Build service
        run: docker compose -f docker-compose.yml build

      - name: Start service
        run: docker compose -f docker-compose.yml up --force-recreate -d
