name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  check-frontend:
    name: Lint frontend code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: cd frontend && npm install --legacy-peer-deps

      - name: Lint code
        run: cd frontend && npm run lint

  build-service:
    name: Build service
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop service
        run: docker compose -f docker-compose.yml down

      - name: Build service
        run: docker compose -f docker-compose.yml build

      - name: Start service
        run: docker compose -f docker-compose.yml up --force-recreate -d

  compile-plugin:
    needs: [check-frontend]
    name: Compile plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: cd frontend && npm install --legacy-peer-deps

      - name: Compile Obsidian plugin
        run: |
          cd frontend
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: obsidian-plugin
          path: frontend/dist