name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    name: Check changed files
    outputs:
      backend: ${{ steps.check_files.outputs.backend }}
      frontend: ${{ steps.check_files.outputs.frontend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: check modified files
        id: check_files
        run: |
            git diff --name-only HEAD^ HEAD > files.txt
            while IFS= read -r file; do
              echo $file
              if [[ $file == frontend/* ]]; then
                echo "frontend service will be rebuilt"
                echo "::set-output name=frontend::true"
              elif [[ $file == backend/* ]]; then
                echo "backend service will be rebuilt"
                echo "::set-output name=backend::true"
              else
                echo "file does not belong to any service"
              fi
            done < files.txt

  check-backend:
    needs: [init]
    if: needs.init.outputs.backend == 'true'
    name: Lint backend code
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 autopep8

      - name: Run Flake8
        run: |
          flake8 --max-line-length=120 backend/

      - name: Run PEP 8 Compliance Check
        run: |
          cd backend
          find -type f -name '*.py' ! -path '*/migrations/*' -exec autopep8 --in-place --aggressive --aggressive '{}' \;

  check-frontend:
    needs: [init]
    if: needs.init.outputs.frontend == 'true'
    name: Lint frontend code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: cd frontend && npm install --legacy-peer-deps

      - name: Lint code
        run: cd frontend && npm run lint

  build-frontend:
    needs: [check-frontend]
    name: Build web service
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Stop service
        run: docker compose -f docker-compose.yml down frontend

      - name: Build service
        run: docker compose -f docker-compose.yml build frontend

      - name: Start service
        run: docker compose -f docker-compose.yml up frontend --force-recreate -d

  build-backend:
    needs: [check-backend]
    name: Build backend service
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_LLM_API_KEY: ${{ secrets.AI_TUNNEL_KEY }}
          file_name: .env
          fail_on_empty: false

      - name: Stop service
        run: docker compose -f docker-compose.yml --env-file .env down backend

      - name: Build service
        run: docker compose -f docker-compose.yml --env-file .env build backend

      - name: Start service
        run: docker compose -f docker-compose.yml --env-file .env up backend --force-recreate -d

  compile-plugin:
    needs: [check-frontend]
    name: Compile plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: cd frontend && npm install --legacy-peer-deps

      - name: Compile Obsidian plugin
        run: |
          cd frontend
          npm run build

          cp manifest.json dist/manifest.json
          tar -cvf obsidian-rag-plugin.tar.gz dist/manifest.json dist/main.js

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: obsidian-rag-plugin
          path: frontend/obsidian-rag-plugin.tar.gz

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Release on GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release create ${SHORT_SHA}
          frontend/obsidian-rag-plugin.tar.gz
          --generate-notes
          --title "Obsidian Rag Plugin #${SHORT_SHA}"