name: Deploy App

on:
  pull_request:

jobs:
  check-backend:
    name: Lint backend code
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: |
          flake8 backend/*

      - name: Run PEP 8 Compliance Check
        run: |
          flake8 --max-line-length=120 backend/*

  check-frontend:
    name: Lint frontend code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: cd frontend && npm install --legacy-peer-deps

      - name: Lint code
        run: cd frontend && npm run lint
